###创建接口
POST http://localhost:8080/testRepeat
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "my": {
    "commonTwoFieldVos": [
      {
        "id": "1",
        "label": "asd"
      },
      {
        "id": "1",
        "label": "  asd "
      }
    ]
  },
  "name": "333",
  "age": 5
}
###
