eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true #是否注册到eureka服务器
    fetch-registry: true #是否可检索
    service-url:
      defaultZone: http://localhost:1111/eureka/ #服务中心
server:
  port: 7777
spring:
  application:
    name: harkwork-gateway
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: hardwork-generator
    api-b:
      path: /api-b/**
      serviceId: hardwork-tomcat